update git-release script

diff --git a/git-release b/git-release
--- a/git-release
+++ b/git-release
@@ -21,6 +21,14 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+# Update version in README.md
+echo "📝 Updating README.md version to $VERSION..."
+sed -i.bak -E "s|(https://img.shields.io/badge/version-)[0-9]+\.[0-9]+\.[0-9]+(-blue.svg)|\1$VERSION\2|" README.md
+if [ $? -ne 0 ]; then
+  echo "❌ Failed to update README version. Aborting."
+  exit 1
+fi
+
 # Commit version bump
 git add package.json
 git commit -m "chore: bump version to $VERSION"
